services:

    db:
        image: dockerrepopath/imagename:tagno.
        restart: always
        environment:
            DB_PASSWORD: root
            
        ports:
            - 8761:3306
        container_name: H2DB
        
    tomcat:
        image: dockerrepopath/imagename:tagno.
      
        restart: always
        environment:
            - JPDA_ADDRESS=7000
            - JPDA_TRANSPORT=dt_socket
        ports:
            - 8888:8080
            - 8443:8443
            - 9000:7000
        container_name: tomcat
        entrypoint: /usr/local/tomcat/bin/catalina.sh jpda run
        depends_on:
            - db
            
